# Generated by Django 2.2.12 on 2020-06-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttoken',
            name='firebaseToken',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
