# Generated by Django 2.2.12 on 2020-06-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200601_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttoken',
            name='firebaseToken',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
