# Generated by Django 2.2.12 on 2020-05-31 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0002_auto_20200528_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='shopping_list',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
